---
# This playbook deploys all site configs

- name: apply base configuration to all nodes
  hosts: all
  remote_user: root

  roles:
  - base

- name: Configure web servers
  hosts: webservers
  remote_user: root

  roles:
  - webservers 
