---
- name: create user using variable
  hosts: all
  vars:
    user: user_var
  tasks:
    - name: create a user {{user}}
      user:
        name: "{{ user }}"   #if variable is the firs item, you need ""
...
   
